// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvhzsqlekvffjyokprxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2aHpzcWxla3ZmZmp5b2twcnh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxOTczMTUsImV4cCI6MjA2OTc3MzMxNX0.gWKQZWqToZbduMN-GvsErdpXtjObrDbL5KK6SaguMM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});